/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BinaryConverterImport } from './routes/binaryConverter'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const BinaryConverterRoute = BinaryConverterImport.update({
  path: '/binaryConverter',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/binaryConverter': {
      id: '/binaryConverter'
      path: '/binaryConverter'
      fullPath: '/binaryConverter'
      preLoaderRoute: typeof BinaryConverterImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  BinaryConverterRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/binaryConverter"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/binaryConverter": {
      "filePath": "binaryConverter.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
